export { Home } from './home'
export { Company, People } from './about'
export { Contact } from './contact'
export { Residential, Commercial } from './services'
export { Equipment, StoneTile } from './resources'
export { Privacy } from './policies/privacy'
export { Cookies } from './policies/cookies'