export { Home } from './home'
export { Company, People } from './about'
export { Contact } from './contact'
export { Residential, Commercial } from './services'
export { Dashboard } from './dashboard'
export { Equipment, StoneTile } from './resources'